config/routes.rb
Rails.application.routes.draw do
  # You can have the root of your site routed with "root"
  root 'landing_page#index'

  get 'profile' => 'users#show'
  get 'users' => 'users#index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :events
  resources :users
  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase


  unless Rails.env.test?
    get '404', :to => 'errors#page_not_found'
    get '422', :to => 'errors#server_error'
    get '500', :to => 'errors#server_error'
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
belongs_to :user

validates :title, length: { minimum: 5 }
validates :description,length: {minimum: 3}
validates :location, length: {minimum: 3 }
validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
has_many :events
validates_uniqueness_of :username
validates :username,length: { minimum: 5 }
validates :password,length: {minimum: 6}
validates :first_name,length: {minimum: 1 }
validates :last_name, length: {minimum: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def page_not_found
    respond_to do |format|
      format.html { render template: 'errors/not_found_error', layout: 'layouts/application', status: 404 }
      format.all  { render nothing: true, status: 404 }
    end
  end

  def server_error
    respond_to do |format|
      format.html { render template: 'errors/internal_server_error', layout: 'layouts/error', status: 500 }
      format.all  { render nothing: true, status: 500}
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def create
    @event = Event.new(event_params)

    @event.save
    redirect_to @event
  end

  def show
    @event = Event.find(params[:id])
  end

  def index
    @user_id = session[:user_id]
    @event = Event.where('user_id = ?', @user_id)
  end

  private
  def event_params
    params.require(:events).permit(:title, :location, :date, :description, :user_id)
  end
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && (user[:password] === params[:session][:password])
      # Log the user in and redirect to the user's show page.
      #render 'new'
      log_in user
      redirect_to user
    else
      # Create an error message.
      flash.now[:danger] = 'Invalid email/password combination'
      render 'sessions/new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path
    else
      render 'new'
    end
  end

  def index
    @users = User.all
  end

  def show
    displayUserEvents
  end

  private
  def user_params
    params.require(:users).permit(:first_name, :last_name, :username, :password)
  end

  def displayUserEvents
   @event = Event.where('user_id = ?',params[:id])
   @user= User.where('id = ?',params[:id])
  end
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
    session[:name] = user.first_name << ' '  << user.last_name
  end

  def current_user
    @current_user ||=  User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/views/events/_events.html.erb
 <table align="center">
        <tr>
          <th>Title</th>
          <th>Location</th>
          <th>Date</th>
          <th>Description</th>

        <% if session[:user_id] == @event[0][:user_id] %>
            <th>Display</th>
            <th>Edit</th>
            <th>Delete</th>
        <% end %>
        </tr>

      <% @event.each do |event| %>
          <tr>
            <td><%= event.title %></td>
            <td><%= event.location %></td>
            <td><%= event.date %></td>
            <td><%= event.description %></td>

            <% if session[:user_id] == event.user_id %>

                <td><%= link_to('Display', event_path(event), :class => 'btn btn-large btn-primary')  %></td>
                <td><%= link_to('Edit',  edit_event_path(event), :class => 'btn btn-large btn-primary')  %></td>
                <td><%= link_to('Destroy', event_path(event), method: :delete,
                                data: { confirm: 'Are you sure?' } , :class => 'btn btn-large btn-primary')  %></td>

            <% end %>
          </tr>
      <% end %>
 </table>

app/views/events/_form.html.erb
<%=  form_for @event  do |f|%>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <p>Woah there...</p>
      <ul>
        <% @event.errors.full_messages.each do |msg| %>
        <li><b><%= msg %></b></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :title, "Title",  class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :location, "Location",  class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :location, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :date, "Date",  class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_select :date, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, "Description",  class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :description, class: 'form-control' %>
    </div>
  </div>
  <%= f.hidden_field :user_id , :value =>  session[:user_id] %>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Submit Event", class: "btn btn-primary" %>
      <%= link_to 'Cancel', user_path(session[:user_id]), :class => 'btn btn-large btn-warning'%>
    </div>
  </div>
<% end %>

app/views/events/edit.html.erb
<div id="wrapper">
  <%= render 'layouts/sidebar' %>
  <div id="page-content-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <div class="btn btn-default" id="menu-toggle">Menu</div>
        </div>
        <div class="main-content">
          <div class="col-md-3 profile-outer">
            <%= image_tag 'profile.jpg', class: 'profile' %>
            <p class="name">Chanel Preston</p>
            <p class="name">13 Events</p>
            <p class="name">24 Followers</p>
          </div>
        </div>
        <div class="col-md-7 event-list">
          <h2>Editing My Event</h2>
					<%= render 'events/form' %>
        </div>
      </div>
      
    </div>
  </div>
</div>

app/views/events/index.html.erb
<table>
  <tr>
    <th>Title</th>
    <th>Location</th>
    <th>Date</th>
    <th>Description</th>
  </tr>

  <% @event.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.location %></td>
        <td><%= event.date %></td>
        <td><%= event.description %></td>
      </tr>
  <% end %>
</table>

app/views/events/new.html.erb
<div id="wrapper">
  <%= render 'layouts/sidebar' %>
  <div id="page-content-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <div class="btn btn-default" id="menu-toggle">Menu</div>
        </div>
        <div class="main-content">
          <div class="col-md-3 profile-outer">
            <%= image_tag 'profile.jpg', class: 'profile' %>
            <p class="name">Chanel Preston</p>
            <p class="name">13 Events</p>
            <p class="name">24 Followers</p>
          </div>
        </div>
        <div class="col-md-7 event-list">
          <h2>My New Event</h2>
					<%= render 'events/form' %>
        </div>
      </div>
      
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div id="wrapper">
	<%= render 'layouts/sidebar' %>
	<div id="page-content-wrapper">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12">
					<div class="btn btn-default" id="menu-toggle">Menu</div>
				</div>
				<div class="main-content">
					<div class="col-md-3 profile-outer">
						<%= image_tag 'profile.jpg', class: 'profile' %>
						<p class="name">Chanel Preston</p>
						<p class="name">13 Events</p>
						<p class="name">24 Followers</p>
					</div>
				</div>
				<div class="col-md-7 event-list">
					
					<h2><%= @event.title %></h4>
					<h4><%= @event.location %></h4>
					<h4><%= @event.date %></h4>
					<p><%= @event.description %></p>
					<%= link_to 'Back', user_path(session[:user_id]), :class => 'btn btn-large btn-primary' %>
					<div>
						<!--<% if @current_user == nil %>
						<%= link_to 'Back', root_path, :class => 'btn btn-large btn-primary'%>
						<% else %>
						<%= link_to 'Back', user_path(session[:user_id]), :class => 'btn btn-large btn-primary'%>
						<% end %>-->
					</div>
				</div>
			</div>
			
		</div>
	</div>
</div>

app/views/landing_page/index.html.erb
<%= render 'layouts/header' %>
 <div id="page-content-wrapper">
            <div class="section-content container-fluid module parallax" id="landing-intro">
                <div class="row text-center landing-statement">
                    <h1 class="text-center">Ultimate Bucket List</h1>
                    <h3>Create your own adventure..</h3>
                </div>
                <div class="row text-center arrow">
                    <a href="" class="fa fa-angle-double-down fa-4x"></a>
                </div>
            </div>

        </div>
        <div class="section-content container-fluid text-center" id="landing-content">
            <div class="row content-service">
                <h2>Our Services</h2>
                <h4><small>A little about would we do</small></h4>    
            </div>
            <div class="row content-service-p">
                <div class="column col-md-4">
                    <i class="fa fa-plus-circle fa-4x"></i>
                    <h4>Create</h4>
                        <p>
                            Lorem ipsum dolor sit amet, ea est ipsum iriure, vim ad mnesarchum complectitur, mel id veri adolescens. Harum electram sed te, te mutat graece propriae est. Ius ei unum movet, ne duo graeci molestiae mnesarchum, eum id salutandi instructior. Lorem appetere molestiae ut eum, mel in consul efficiendi.
                        </p>
                </div>
                <div class="column col-md-4">
                    <i class="fa fa-trash fa-4x"></i>
                    <h4>Delete</h4>
                    <p>
                    Lorem ipsum dolor sit amet, ea est ipsum iriure, vim ad mnesarchum complectitur, mel id veri adolescens. Harum electram sed te, te mutat graece propriae est. Ius ei unum movet, ne duo graeci molestiae mnesarchum, eum id salutandi instructior. Lorem appetere molestiae ut eum, mel in consul efficiendi.
                    </p>
                </div>
                <i class="fa fa-share-alt fa-4x"></i>
                <h4>Connect</h4>
                <div class="column col-md-4">
                    <p>
                    Lorem ipsum dolor sit amet, ea est ipsum iriure, vim ad mnesarchum complectitur, mel id veri adolescens. Harum electram sed te, te mutat graece propriae est. Ius ei unum movet, ne duo graeci molestiae mnesarchum, eum id salutandi instructior. Lorem appetere molestiae ut eum, mel in consul efficiendi.    
                    </p>                
                </div>
            </div>
        </div>

app/views/layouts/_header.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <!-- for the scroll-->
      <a class="navbar-brand page-scroll" href="#page-top"></a>
      <%= link_to "The Ultimate Bucket List", root_path, :class => 'navbar-brand page-scroll' %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav">
        <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
        <li class="hidden">
          <a class="page-scroll" href="#page-top"></a>
        </li>
        <li>
          <a class="page-scroll" href="#about">About</a>
        </li>
        <li>
          <a class="page-scroll" href="#services">Features</a>
        </li>
        <li>
          <a class="page-scroll" href="#contact">Contact</a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Sign Up", new_user_path %></li>
        <li><%= link_to "Log in", login_path %></li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/layouts/_sidebar.html.erb
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <li class="sidebar-brand"><%= link_to "The Ultimate Bucket List", root_path %></li>
    <li><%= link_to "My Profile", user_path(session[:user_id]) %></li>
    <li><%= link_to "Add New Event", new_event_path%></li>
    <li><%= link_to "My Friends", users_path %></li>
    <li> <%= link_to "Logout", logout_path, method: "delete" %></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BucketList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">

  
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/error.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= BucketList %></title>
  <%= csrf_meta_tags %>
  <style>
      body {
          background: #fff;
          font-family: Helvetica, Arial, Sans-Serif;
          font-size: 14px;
      }
      .error_container {
          display: block;
          margin: auto;
          margin: 10% auto 0 auto;
          width: 40%;
      }
      .error_container .error {
          display: block;
          text-align: center;
      }
      .error_container .error img {
          display: block;
          margin: 0 auto 25px auto;
      }
      .error_container .message strong {
          font-weight: bold;
          color: #f00;
      }
      .error_container .contact_info {
          display: block;
          text-align: center;
          margin: 25px 0 0 0;
      }
      .error_container .contact_info a {
          display: inline-block;
          margin: 0 5px;
          opacity: 0.4;
          transition: opacity 0.15s ease;
      }
      .error_container .contact_info a:hover {
          opacity: 0.8;
      }
  </style>
</head>
<body>
<div class="error_container">
  <%= yield %>
</div>
</body>
</html>

app/views/users/index.html.erb
<div id="wrapper">
  <%= render 'layouts/sidebar' %>
  <div id="page-content-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <div class="btn btn-default" id="menu-toggle">Menu</div>
        </div>
        <div class="main-content">
          <div class="col-md-3 profile-outer">
            <%= image_tag 'profile.jpg', class: 'profile' %>
            <p class="name">Chanel Preston</p>
            <p class="name">13 Events</p>
            <p class="name">24 Followers</p>
          </div>
        </div>
        <div class="col-md-7 event-list">
          <h2>My Friends</h2>
          <hr>
          <% @users.each do |user| %>
            <% if @current_user == nil || session[:user_id] != user.id %>
              <h4><%= user.first_name << ' ' << user.last_name %></h4>
              <p>
                <%= link_to 'View Profile', user_path(user), 
                    :class => 'btn btn-large btn-primary' %>
              </p>
            <% end %>
          <% end %>
        </div>
      </div>
      
    </div>
  </div>
</div>

app/views/users/new.html.erb
<%= render 'layouts/header' %>
<div class="signup-page">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h3>Sign Up</h3>
        <%= form_for :users, url: users_path do |f| %>
        <% if @user.errors.any? %>
          <div id="error_explanation">
            <p>Woah there...</p>
            <ul>
              <% @user.errors.full_messages.each do |msg| %>
              <li><b><%= msg %></b></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group signup-form-group">
          <%= f.label :first_name, "First Name",  class: "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.text_field :first_name, class: 'form-control signup-form-control' %>
          </div>
        </div>
        <div class="form-group signup-form-group">
          <%= f.label :last_name, "Last Name",  class: "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.text_field :last_name, class: 'form-control signup-form-control' %>
          </div>
        </div>
        
        <div class="form-group signup-form-group">
          <%= f.label :username, "User Name",  class: "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.text_field :username, class: 'form-control signup-form-control' %>
          </div>
        </div>
        <div class="form-group signup-form-group">
          <%= f.label :password, "Password", class: "col-sm-2 control-label" %>
          <div class="col-sm-10">
            <%= f.password_field :password, class: 'form-control signup-form-control' %>
          </div>
        </div>
        <div class="form-group signup-form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit "Create my Account", class: "btn btn-lg btn-primary" %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/profile.html.erb
<%= render 'layouts/header' %>
<h1>Welcome to your Profile  <%=  session[:name] %>!</h1>

<h3>Events</h3>
<%= render 'events/events' %>

app/views/users/show.html.erb
<div id="wrapper">
  <%= render 'layouts/sidebar' %>
  <div id="page-content-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <div class="btn btn-default" id="menu-toggle">Menu</div>
        </div>
        <div class="main-content">
          <div class="col-md-3 profile-outer">
            <%= image_tag 'profile.jpg', class: 'profile' %>
            <p class="name">Chanel Preston</p>
            <p class="name">13 Events</p>
            <p class="name">24 Followers</p>
            </div>
          </div>
          <div class="col-md-7 event-list">
            <% if @user != nil && session[:user_id] == @user[0][:id] %>
						    <h2>Welcome to your Profile <%= session[:name] %>!</h2>
						<% else %>
						    <h2>Profile <%= @user[0][:first_name] << ' ' << @user[0][:last_name] %></h2>
						<% end %>

						<% if @event.any? %>
						     <%= render 'events/events' %>
						<% elsif @event.count == 0 && @user.any?%>
								<p>No New Events</p>
						    <%= link_to "Add New Event", new_event_path %>
						<% end %>

          <div>
            <!--<% if @current_user == nil %>
              <%= link_to 'Back', root_path, :class => 'btn btn-large btn-primary'%>
            <% else %>
              <%= link_to 'Back', user_path(session[:user_id]), :class => 'btn btn-large btn-primary'%>
            <% end %>-->
          </div>
        </div>
      </div>
      
    </div>
  </div>
</div>